
name: Java CI with Maven

on:
  push:
    branches:
      - '*'  # 所有分支
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write
  discussions: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CatSeedLogin
        path: target/CatSeedLogin*.jar

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2.0.8
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/CatSeedLogin*.jar
